 namespace ConsoleApp49
{
    #region class HospitalSeeder
    public static class HospitalSeeder
    {
        public static List<Hospital> Hospitals { get; } = new()
        {
            new() { Id = 1, Name = "Cairo University Hospitals", Address = "Kasr Al Ainy St, Cairo", FoundedYear = 1946, IsGovernmentFunded = false },
            new() { Id = 2, Name = "Alexandria Main University Hospital", Address = "Smouha, Alexandria", FoundedYear = 1947, IsGovernmentFunded = true },
            new() { Id = 3, Name = "Giza Teaching Hospital", Address = "Haram St, Giza", FoundedYear = 1948, IsGovernmentFunded = false },
            new() { Id = 4, Name = "Mansoura University Hospital", Address = "Gomhoria St, Mansoura", FoundedYear = 1949, IsGovernmentFunded = true },
            new() { Id = 5, Name = "Tanta University Hospital", Address = "El Geish St, Tanta", FoundedYear = 1950, IsGovernmentFunded = false },
            new() { Id = 6, Name = "Aswan University Hospital", Address = "Corniche El Nile, Aswan", FoundedYear = 1951, IsGovernmentFunded = true },
            new() { Id = 7, Name = "Luxor International Hospital", Address = "Karnak Rd, Luxor", FoundedYear = 1952, IsGovernmentFunded = false },
            new() { Id = 8, Name = "Suez Canal University Hospital", Address = "University St, Suez", FoundedYear = 1953, IsGovernmentFunded = true },
            new() { Id = 9, Name = "Ismailia Specialist Hospital", Address = "Sheikh Zayed St, Ismailia", FoundedYear = 1954, IsGovernmentFunded = false },
            new() { Id = 10, Name = "Port Said General Hospital", Address = "23 July St, Port Said", FoundedYear = 1955, IsGovernmentFunded = true },
            new() { Id = 11, Name = "Zagazig University Hospital", Address = "University Campus, Zagazig", FoundedYear = 1956, IsGovernmentFunded = false },
            new() { Id = 12, Name = "Minya University Hospital", Address = "Corniche, Minya", FoundedYear = 1957, IsGovernmentFunded = true },
            new() { Id = 13, Name = "Assiut University Hospital", Address = "University Blvd, Assiut", FoundedYear = 1958, IsGovernmentFunded = false },
            new() { Id = 14, Name = "Damietta General Hospital", Address = "Sea St, Damietta", FoundedYear = 1959, IsGovernmentFunded = true },
            new() { Id = 15, Name = "Hurghada Red Sea Hospital", Address = "El Mamsha, Hurghada", FoundedYear = 1960, IsGovernmentFunded = false },
            new() { Id = 16, Name = "Sharm El Sheikh International Hospital", Address = "Peace Rd, Sharm El Sheikh", FoundedYear = 1961, IsGovernmentFunded = true },
            new() { Id = 17, Name = "Banha Teaching Hospital", Address = "Faculty of Medicine, Banha", FoundedYear = 1962, IsGovernmentFunded = false },
            new() { Id = 18, Name = "Damanhur Medical Complex", Address = "Abou El Abbas, Damanhur", FoundedYear = 1963, IsGovernmentFunded = true },
            new() { Id = 19, Name = "Qena General Hospital", Address = "Hospital St, Qena", FoundedYear = 1964, IsGovernmentFunded = false },
            new() { Id = 20, Name = "Sohag University Hospital", Address = "University Rd, Sohag", FoundedYear = 1965, IsGovernmentFunded = true },
            new() { Id = 21, Name = "Fayoum University Hospital", Address = "El Horreya St, Fayoum", FoundedYear = 1966, IsGovernmentFunded = false },
            new() { Id = 22, Name = "Beni Suef General Hospital", Address = "Nile Corniche, Beni Suef", FoundedYear = 1967, IsGovernmentFunded = true },
            new() { Id = 23, Name = "Kafr El Sheikh Medical Center", Address = "Central Square, Kafr El Sheikh", FoundedYear = 1968, IsGovernmentFunded = false },
            new() { Id = 24, Name = "Arish Central Hospital", Address = "Sinai Rd, Arish", FoundedYear = 1969, IsGovernmentFunded = true },
            new() { Id = 25, Name = "Marsa Matrouh Coastal Hospital", Address = "Corniche, Marsa Matrouh", FoundedYear = 1970, IsGovernmentFunded = false },
            new() { Id = 26, Name = "Dar Al Fouad Hospital", Address = "26th of July Corridor, 6th of October", FoundedYear = 1971, IsGovernmentFunded = true },
            new() { Id = 27, Name = "Cleopatra Hospital", Address = "Rehab City, New Cairo", FoundedYear = 1972, IsGovernmentFunded = false },
            new() { Id = 28, Name = "Saudi German Hospital Cairo", Address = "Dokki, Giza", FoundedYear = 1973, IsGovernmentFunded = true },
            new() { Id = 29, Name = "Andalusia Hospital", Address = "Smouha Medical Park, Alexandria", FoundedYear = 1974, IsGovernmentFunded = false },
            new() { Id = 30, Name = "Air Force Specialized Hospital", Address = "Abbasia, Cairo", FoundedYear = 1975, IsGovernmentFunded = true },
            new() { Id = 31, Name = "Nasser Institute Hospital", Address = "Shoubra, Cairo", FoundedYear = 1976, IsGovernmentFunded = false },
            new() { Id = 32, Name = "El Demerdash Hospital", Address = "Abbasia Square, Cairo", FoundedYear = 1977, IsGovernmentFunded = true },
            new() { Id = 33, Name = "Kasr Al Ainy Hospital", Address = "Kasr Al Ainy, Cairo", FoundedYear = 1978, IsGovernmentFunded = false },
            new() { Id = 34, Name = "Ain Shams Specialized Hospital", Address = "Abbasia, Cairo", FoundedYear = 1979, IsGovernmentFunded = true },
            new() { Id = 35, Name = "El Salam International Hospital", Address = "Maadi, Cairo", FoundedYear = 1980, IsGovernmentFunded = false },
            new() { Id = 36, Name = "Wadi El Neel Hospital", Address = "Nasr City, Cairo", FoundedYear = 1981, IsGovernmentFunded = true },
            new() { Id = 37, Name = "As-Salam Oncology Center", Address = "Heliopolis, Cairo", FoundedYear = 1982, IsGovernmentFunded = false },
            new() { Id = 38, Name = "Misr International Hospital", Address = "Mohandessin, Cairo", FoundedYear = 1983, IsGovernmentFunded = true },
            new() { Id = 39, Name = "Nile Badrawy Hospital", Address = "Dokki, Cairo", FoundedYear = 1984, IsGovernmentFunded = false },
            new() { Id = 40, Name = "Police Hospital Agouza", Address = "Agouza, Cairo", FoundedYear = 1985, IsGovernmentFunded = true },
            new() { Id = 41, Name = "Military Production Hospital", Address = "Helwan, Cairo", FoundedYear = 1986, IsGovernmentFunded = false },
            new() { Id = 42, Name = "Coptic Hospital", Address = "Abbasia, Cairo", FoundedYear = 1987, IsGovernmentFunded = true },
            new() { Id = 43, Name = "Italian Hospital Cairo", Address = "Faggala, Cairo", FoundedYear = 1988, IsGovernmentFunded = false },
            new() { Id = 44, Name = "Jewish Hospital Abbasia", Address = "Abbasia, Cairo", FoundedYear = 1989, IsGovernmentFunded = true },
            new() { Id = 45, Name = "Anglo-American Hospital", Address = "Zamalek, Cairo", FoundedYear = 1990, IsGovernmentFunded = false },
            new() { Id = 46, Name = "New Cairo Specialized Hospital", Address = "New Cairo", FoundedYear = 1991, IsGovernmentFunded = true },
            new() { Id = 47, Name = "Sheikh Zayed Medical Complex", Address = "Sheikh Zayed City", FoundedYear = 1992, IsGovernmentFunded = false },
            new() { Id = 48, Name = "October 6 University Hospital", Address = "6th of October City", FoundedYear = 1993, IsGovernmentFunded = true },
            new() { Id = 49, Name = "Helwan General Hospital", Address = "Helwan", FoundedYear = 1994, IsGovernmentFunded = false },
            new() { Id = 50, Name = "Mahalla Spinning Hospital", Address = "Mahalla El Kubra", FoundedYear = 1995, IsGovernmentFunded = true }
        };

        public static List<Department> Departments { get; } = new()
        {
            new() { Id = 1, Name = "Cardiology", AnnualBudget = 212500, FloorNumber = 1 },
            new() { Id = 2, Name = "Pediatrics", AnnualBudget = 225000, FloorNumber = 2 },
            new() { Id = 3, Name = "Orthopedics", AnnualBudget = 237500, FloorNumber = 3 },
            new() { Id = 4, Name = "Emergency", AnnualBudget = 250000, FloorNumber = 4 },
            new() { Id = 5, Name = "Neurology", AnnualBudget = 262500, FloorNumber = 5 },
            new() { Id = 6, Name = "Oncology", AnnualBudget = 275000, FloorNumber = 6 },
            new() { Id = 7, Name = "Dermatology", AnnualBudget = 287500, FloorNumber = 7 },
            new() { Id = 8, Name = "Radiology", AnnualBudget = 300000, FloorNumber = 0 },
            new() { Id = 9, Name = "Maternity", AnnualBudget = 312500, FloorNumber = 1 },
            new() { Id = 10, Name = "Surgery", AnnualBudget = 325000, FloorNumber = 2 },
            new() { Id = 11, Name = "Urology", AnnualBudget = 337500, FloorNumber = 3 },
            new() { Id = 12, Name = "ENT", AnnualBudget = 350000, FloorNumber = 4 },
            new() { Id = 13, Name = "Ophthalmology", AnnualBudget = 362500, FloorNumber = 5 },
            new() { Id = 14, Name = "Psychiatry", AnnualBudget = 375000, FloorNumber = 6 },
            new() { Id = 15, Name = "Gastroenterology", AnnualBudget = 387500, FloorNumber = 7 },
            new() { Id = 16, Name = "Nephrology", AnnualBudget = 400000, FloorNumber = 0 },
            new() { Id = 17, Name = "Pulmonology", AnnualBudget = 412500, FloorNumber = 1 },
            new() { Id = 18, Name = "Hematology", AnnualBudget = 425000, FloorNumber = 2 },
            new() { Id = 19, Name = "Rheumatology", AnnualBudget = 437500, FloorNumber = 3 },
            new() { Id = 20, Name = "Endocrinology", AnnualBudget = 450000, FloorNumber = 4 },
            new() { Id = 21, Name = "Plastic Surgery", AnnualBudget = 462500, FloorNumber = 5 },
            new() { Id = 22, Name = "Anesthesiology", AnnualBudget = 475000, FloorNumber = 6 },
            new() { Id = 23, Name = "Pathology", AnnualBudget = 487500, FloorNumber = 7 },
            new() { Id = 24, Name = "Internal Medicine", AnnualBudget = 500000, FloorNumber = 0 },
            new() { Id = 25, Name = "Family Medicine", AnnualBudget = 512500, FloorNumber = 1 },
            new() { Id = 26, Name = "Geriatrics", AnnualBudget = 525000, FloorNumber = 2 },
            new() { Id = 27, Name = "Infectious Diseases", AnnualBudget = 537500, FloorNumber = 3 },
            new() { Id = 28, Name = "Physical Therapy", AnnualBudget = 550000, FloorNumber = 4 },
            new() { Id = 29, Name = "Nutrition", AnnualBudget = 562500, FloorNumber = 5 },
            new() { Id = 30, Name = "Pharmacy Ops", AnnualBudget = 575000, FloorNumber = 6 },
            new() { Id = 31, Name = "Dialysis", AnnualBudget = 587500, FloorNumber = 7 },
            new() { Id = 32, Name = "Burn Unit", AnnualBudget = 600000, FloorNumber = 0 },
            new() { Id = 33, Name = "ICU Central", AnnualBudget = 612500, FloorNumber = 1 },
            new() { Id = 34, Name = "Neonatal", AnnualBudget = 625000, FloorNumber = 2 },
            new() { Id = 35, Name = "Cardiac Surgery", AnnualBudget = 637500, FloorNumber = 3 },
            new() { Id = 36, Name = "Vascular", AnnualBudget = 650000, FloorNumber = 4 },
            new() { Id = 37, Name = "Thoracic", AnnualBudget = 662500, FloorNumber = 5 },
            new() { Id = 38, Name = "Maxillofacial", AnnualBudget = 675000, FloorNumber = 6 },
            new() { Id = 39, Name = "Allergy", AnnualBudget = 687500, FloorNumber = 7 },
            new() { Id = 40, Name = "Immunology", AnnualBudget = 700000, FloorNumber = 0 },
            new() { Id = 41, Name = "Genetics", AnnualBudget = 712500, FloorNumber = 1 },
            new() { Id = 42, Name = "Palliative Care", AnnualBudget = 725000, FloorNumber = 2 },
            new() { Id = 43, Name = "Occupational Health", AnnualBudget = 737500, FloorNumber = 3 },
            new() { Id = 44, Name = "Sports Medicine", AnnualBudget = 750000, FloorNumber = 4 },
            new() { Id = 45, Name = "Pain Management", AnnualBudget = 762500, FloorNumber = 5 },
            new() { Id = 46, Name = "Sleep Medicine", AnnualBudget = 775000, FloorNumber = 6 },
            new() { Id = 47, Name = "Transplant", AnnualBudget = 787500, FloorNumber = 7 },
            new() { Id = 48, Name = "Trauma", AnnualBudget = 800000, FloorNumber = 0 },
            new() { Id = 49, Name = "Stroke Unit", AnnualBudget = 812500, FloorNumber = 1 },
            new() { Id = 50, Name = "Day Surgery", AnnualBudget = 825000, FloorNumber = 2 }
        };

        public static List<Doctor> Doctors { get; } = new()
        {
            new() { Id = 1, Name = "Dr. Ahmed Salah", Specialty = "Cardiology", YearsOfExperience = 2, Salary = 81500, IsAvailable = true, DepartmentId = 1 },
            new() { Id = 2, Name = "Dr. Mona Samir", Specialty = "Pediatrics", YearsOfExperience = 3, Salary = 83000, IsAvailable = true, DepartmentId = 2 },
            new() { Id = 3, Name = "Dr. Karim Khalil", Specialty = "Orthopedics", YearsOfExperience = 4, Salary = 84500, IsAvailable = false, DepartmentId = 3 },
            new() { Id = 4, Name = "Dr. Yara Adel", Specialty = "Emergency", YearsOfExperience = 5, Salary = 86000, IsAvailable = true, DepartmentId = 4 },
            new() { Id = 5, Name = "Dr. Tarek Said", Specialty = "Neurology", YearsOfExperience = 6, Salary = 87500, IsAvailable = true, DepartmentId = 5 },
            new() { Id = 6, Name = "Dr. Salma Mansour", Specialty = "Oncology", YearsOfExperience = 7, Salary = 89000, IsAvailable = false, DepartmentId = 6 },
            new() { Id = 7, Name = "Dr. Omar Zaki", Specialty = "Dermatology", YearsOfExperience = 8, Salary = 90500, IsAvailable = true, DepartmentId = 7 },
            new() { Id = 8, Name = "Dr. Nour Barakat", Specialty = "Radiology", YearsOfExperience = 9, Salary = 92000, IsAvailable = true, DepartmentId = 8 },
            new() { Id = 9, Name = "Dr. Sara Ashraf", Specialty = "General Practice", YearsOfExperience = 10, Salary = 93500, IsAvailable = false, DepartmentId = 9 },
            new() { Id = 10, Name = "Dr. Mostafa Shaaban", Specialty = "Surgery", YearsOfExperience = 11, Salary = 95000, IsAvailable = true, DepartmentId = 10 },
            new() { Id = 11, Name = "Dr. Laila Salah", Specialty = "Urology", YearsOfExperience = 12, Salary = 96500, IsAvailable = true, DepartmentId = 11 },
            new() { Id = 12, Name = "Dr. Hoda Samir", Specialty = "ENT", YearsOfExperience = 13, Salary = 98000, IsAvailable = false, DepartmentId = 12 },
            new() { Id = 13, Name = "Dr. Youssef Khalil", Specialty = "Ophthalmology", YearsOfExperience = 14, Salary = 99500, IsAvailable = true, DepartmentId = 13 },
            new() { Id = 14, Name = "Dr. Amina Adel", Specialty = "Psychiatry", YearsOfExperience = 15, Salary = 101000, IsAvailable = true, DepartmentId = 14 },
            new() { Id = 15, Name = "Dr. Hassan Said", Specialty = "Gastroenterology", YearsOfExperience = 16, Salary = 102500, IsAvailable = false, DepartmentId = 15 },
            new() { Id = 16, Name = "Dr. Fatma Mansour", Specialty = "Nephrology", YearsOfExperience = 17, Salary = 104000, IsAvailable = true, DepartmentId = 16 },
            new() { Id = 17, Name = "Dr. Ali Zaki", Specialty = "Pulmonology", YearsOfExperience = 18, Salary = 105500, IsAvailable = true, DepartmentId = 17 },
            new() { Id = 18, Name = "Dr. Dina Barakat", Specialty = "Hematology", YearsOfExperience = 19, Salary = 107000, IsAvailable = false, DepartmentId = 18 },
            new() { Id = 19, Name = "Dr. Rami Ashraf", Specialty = "Rheumatology", YearsOfExperience = 20, Salary = 108500, IsAvailable = true, DepartmentId = 19 },
            new() { Id = 20, Name = "Dr. Heba Shaaban", Specialty = "Endocrinology", YearsOfExperience = 21, Salary = 110000, IsAvailable = true, DepartmentId = 20 },
            new() { Id = 21, Name = "Dr. Mahmoud Salah", Specialty = "Plastic Surgery", YearsOfExperience = 22, Salary = 111500, IsAvailable = false, DepartmentId = 21 },
            new() { Id = 22, Name = "Dr. Nadine Samir", Specialty = "Anesthesiology", YearsOfExperience = 23, Salary = 113000, IsAvailable = true, DepartmentId = 22 },
            new() { Id = 23, Name = "Dr. Khaled Khalil", Specialty = "Internal Medicine", YearsOfExperience = 24, Salary = 114500, IsAvailable = true, DepartmentId = 23 },
            new() { Id = 24, Name = "Dr. Rania Adel", Specialty = "Family Medicine", YearsOfExperience = 25, Salary = 116000, IsAvailable = false, DepartmentId = 24 },
            new() { Id = 25, Name = "Dr. Samir Said", Specialty = "Geriatrics", YearsOfExperience = 26, Salary = 117500, IsAvailable = true, DepartmentId = 25 },
            new() { Id = 26, Name = "Dr. Layla Mansour", Specialty = "Cardiology", YearsOfExperience = 27, Salary = 119000, IsAvailable = true, DepartmentId = 26 },
            new() { Id = 27, Name = "Dr. Fady Zaki", Specialty = "Pediatrics", YearsOfExperience = 28, Salary = 120500, IsAvailable = false, DepartmentId = 27 },
            new() { Id = 28, Name = "Dr. Farida Barakat", Specialty = "Orthopedics", YearsOfExperience = 29, Salary = 122000, IsAvailable = true, DepartmentId = 28 },
            new() { Id = 29, Name = "Dr. Walid Ashraf", Specialty = "Emergency", YearsOfExperience = 30, Salary = 123500, IsAvailable = true, DepartmentId = 29 },
            new() { Id = 30, Name = "Dr. Hanan Shaaban", Specialty = "Neurology", YearsOfExperience = 1, Salary = 125000, IsAvailable = false, DepartmentId = 30 },
            new() { Id = 31, Name = "Dr. Ziad Salah", Specialty = "Oncology", YearsOfExperience = 2, Salary = 126500, IsAvailable = true, DepartmentId = 31 },
            new() { Id = 32, Name = "Dr. Marwa Samir", Specialty = "Dermatology", YearsOfExperience = 3, Salary = 128000, IsAvailable = true, DepartmentId = 32 },
            new() { Id = 33, Name = "Dr. Bassem Khalil", Specialty = "Radiology", YearsOfExperience = 4, Salary = 129500, IsAvailable = false, DepartmentId = 33 },
            new() { Id = 34, Name = "Dr. Noha Adel", Specialty = "General Practice", YearsOfExperience = 5, Salary = 131000, IsAvailable = true, DepartmentId = 34 },
            new() { Id = 35, Name = "Dr. Sherif Said", Specialty = "Surgery", YearsOfExperience = 6, Salary = 132500, IsAvailable = true, DepartmentId = 35 },
            new() { Id = 36, Name = "Dr. Ghada Mansour", Specialty = "Urology", YearsOfExperience = 7, Salary = 134000, IsAvailable = false, DepartmentId = 36 },
            new() { Id = 37, Name = "Dr. Amr Zaki", Specialty = "ENT", YearsOfExperience = 8, Salary = 135500, IsAvailable = true, DepartmentId = 37 },
            new() { Id = 38, Name = "Dr. Reem Barakat", Specialty = "Ophthalmology", YearsOfExperience = 9, Salary = 137000, IsAvailable = true, DepartmentId = 38 },
            new() { Id = 39, Name = "Dr. Hisham Ashraf", Specialty = "Psychiatry", YearsOfExperience = 10, Salary = 138500, IsAvailable = false, DepartmentId = 39 },
            new() { Id = 40, Name = "Dr. Dalia Shaaban", Specialty = "Gastroenterology", YearsOfExperience = 11, Salary = 140000, IsAvailable = true, DepartmentId = 40 },
            new() { Id = 41, Name = "Dr. Ehab Salah", Specialty = "Nephrology", YearsOfExperience = 12, Salary = 141500, IsAvailable = true, DepartmentId = 41 },
            new() { Id = 42, Name = "Dr. Mayada Samir", Specialty = "Pulmonology", YearsOfExperience = 13, Salary = 143000, IsAvailable = false, DepartmentId = 42 },
            new() { Id = 43, Name = "Dr. Tamer Khalil", Specialty = "Hematology", YearsOfExperience = 14, Salary = 144500, IsAvailable = true, DepartmentId = 43 },
            new() { Id = 44, Name = "Dr. Shereen Adel", Specialty = "Rheumatology", YearsOfExperience = 15, Salary = 146000, IsAvailable = true, DepartmentId = 44 },
            new() { Id = 45, Name = "Dr. Adel Said", Specialty = "Endocrinology", YearsOfExperience = 16, Salary = 147500, IsAvailable = false, DepartmentId = 45 },
            new() { Id = 46, Name = "Dr. Inas Mansour", Specialty = "Plastic Surgery", YearsOfExperience = 17, Salary = 149000, IsAvailable = true, DepartmentId = 46 },
            new() { Id = 47, Name = "Dr. Magdy Zaki", Specialty = "Anesthesiology", YearsOfExperience = 18, Salary = 150500, IsAvailable = true, DepartmentId = 47 },
            new() { Id = 48, Name = "Dr. Hala Barakat", Specialty = "Internal Medicine", YearsOfExperience = 19, Salary = 152000, IsAvailable = false, DepartmentId = 48 },
            new() { Id = 49, Name = "Dr. Fares Ashraf", Specialty = "Family Medicine", YearsOfExperience = 20, Salary = 153500, IsAvailable = true, DepartmentId = 49 },
            new() { Id = 50, Name = "Dr. Jana Shaaban", Specialty = "Geriatrics", YearsOfExperience = 21, Salary = 155000, IsAvailable = true, DepartmentId = 50 }
        };

        public static List<Nurse> Nurses { get; } = new()
        {
            new() { Id = 1, Name = "Nurse Nour Barakat", ShiftHoursPerWeek = 34, Salary = 35400, IsOnDuty = false, DepartmentId = 1 },
            new() { Id = 2, Name = "Nurse Sara Ashraf", ShiftHoursPerWeek = 36, Salary = 35800, IsOnDuty = true, DepartmentId = 2 },
            new() { Id = 3, Name = "Nurse Mostafa Shaaban", ShiftHoursPerWeek = 38, Salary = 36200, IsOnDuty = false, DepartmentId = 3 },
            new() { Id = 4, Name = "Nurse Laila Salah", ShiftHoursPerWeek = 40, Salary = 36600, IsOnDuty = true, DepartmentId = 4 },
            new() { Id = 5, Name = "Nurse Hoda Samir", ShiftHoursPerWeek = 32, Salary = 37000, IsOnDuty = false, DepartmentId = 5 },
            new() { Id = 6, Name = "Nurse Youssef Khalil", ShiftHoursPerWeek = 34, Salary = 37400, IsOnDuty = true, DepartmentId = 6 },
            new() { Id = 7, Name = "Nurse Amina Adel", ShiftHoursPerWeek = 36, Salary = 37800, IsOnDuty = false, DepartmentId = 7 },
            new() { Id = 8, Name = "Nurse Hassan Said", ShiftHoursPerWeek = 38, Salary = 38200, IsOnDuty = true, DepartmentId = 8 },
            new() { Id = 9, Name = "Nurse Fatma Mansour", ShiftHoursPerWeek = 40, Salary = 38600, IsOnDuty = false, DepartmentId = 9 },
            new() { Id = 10, Name = "Nurse Ali Zaki", ShiftHoursPerWeek = 32, Salary = 39000, IsOnDuty = true, DepartmentId = 10 },
            new() { Id = 11, Name = "Nurse Dina Barakat", ShiftHoursPerWeek = 34, Salary = 39400, IsOnDuty = false, DepartmentId = 11 },
            new() { Id = 12, Name = "Nurse Rami Ashraf", ShiftHoursPerWeek = 36, Salary = 39800, IsOnDuty = true, DepartmentId = 12 },
            new() { Id = 13, Name = "Nurse Heba Shaaban", ShiftHoursPerWeek = 38, Salary = 40200, IsOnDuty = false, DepartmentId = 13 },
            new() { Id = 14, Name = "Nurse Mahmoud Salah", ShiftHoursPerWeek = 40, Salary = 40600, IsOnDuty = true, DepartmentId = 14 },
            new() { Id = 15, Name = "Nurse Nadine Samir", ShiftHoursPerWeek = 32, Salary = 41000, IsOnDuty = false, DepartmentId = 15 },
            new() { Id = 16, Name = "Nurse Khaled Khalil", ShiftHoursPerWeek = 34, Salary = 41400, IsOnDuty = true, DepartmentId = 16 },
            new() { Id = 17, Name = "Nurse Rania Adel", ShiftHoursPerWeek = 36, Salary = 41800, IsOnDuty = false, DepartmentId = 17 },
            new() { Id = 18, Name = "Nurse Samir Said", ShiftHoursPerWeek = 38, Salary = 42200, IsOnDuty = true, DepartmentId = 18 },
            new() { Id = 19, Name = "Nurse Layla Mansour", ShiftHoursPerWeek = 40, Salary = 42600, IsOnDuty = false, DepartmentId = 19 },
            new() { Id = 20, Name = "Nurse Fady Zaki", ShiftHoursPerWeek = 32, Salary = 43000, IsOnDuty = true, DepartmentId = 20 },
            new() { Id = 21, Name = "Nurse Farida Barakat", ShiftHoursPerWeek = 34, Salary = 43400, IsOnDuty = false, DepartmentId = 21 },
            new() { Id = 22, Name = "Nurse Walid Ashraf", ShiftHoursPerWeek = 36, Salary = 43800, IsOnDuty = true, DepartmentId = 22 },
            new() { Id = 23, Name = "Nurse Hanan Shaaban", ShiftHoursPerWeek = 38, Salary = 44200, IsOnDuty = false, DepartmentId = 23 },
            new() { Id = 24, Name = "Nurse Ziad Salah", ShiftHoursPerWeek = 40, Salary = 44600, IsOnDuty = true, DepartmentId = 24 },
            new() { Id = 25, Name = "Nurse Marwa Samir", ShiftHoursPerWeek = 32, Salary = 45000, IsOnDuty = false, DepartmentId = 25 },
            new() { Id = 26, Name = "Nurse Bassem Khalil", ShiftHoursPerWeek = 34, Salary = 45400, IsOnDuty = true, DepartmentId = 26 },
            new() { Id = 27, Name = "Nurse Noha Adel", ShiftHoursPerWeek = 36, Salary = 45800, IsOnDuty = false, DepartmentId = 27 },
            new() { Id = 28, Name = "Nurse Sherif Said", ShiftHoursPerWeek = 38, Salary = 46200, IsOnDuty = true, DepartmentId = 28 },
            new() { Id = 29, Name = "Nurse Ghada Mansour", ShiftHoursPerWeek = 40, Salary = 46600, IsOnDuty = false, DepartmentId = 29 },
            new() { Id = 30, Name = "Nurse Amr Zaki", ShiftHoursPerWeek = 32, Salary = 47000, IsOnDuty = true, DepartmentId = 30 },
            new() { Id = 31, Name = "Nurse Reem Barakat", ShiftHoursPerWeek = 34, Salary = 47400, IsOnDuty = false, DepartmentId = 31 },
            new() { Id = 32, Name = "Nurse Hisham Ashraf", ShiftHoursPerWeek = 36, Salary = 47800, IsOnDuty = true, DepartmentId = 32 },
            new() { Id = 33, Name = "Nurse Dalia Shaaban", ShiftHoursPerWeek = 38, Salary = 48200, IsOnDuty = false, DepartmentId = 33 },
            new() { Id = 34, Name = "Nurse Ehab Salah", ShiftHoursPerWeek = 40, Salary = 48600, IsOnDuty = true, DepartmentId = 34 },
            new() { Id = 35, Name = "Nurse Mayada Samir", ShiftHoursPerWeek = 32, Salary = 49000, IsOnDuty = false, DepartmentId = 35 },
            new() { Id = 36, Name = "Nurse Tamer Khalil", ShiftHoursPerWeek = 34, Salary = 49400, IsOnDuty = true, DepartmentId = 36 },
            new() { Id = 37, Name = "Nurse Shereen Adel", ShiftHoursPerWeek = 36, Salary = 49800, IsOnDuty = false, DepartmentId = 37 },
            new() { Id = 38, Name = "Nurse Adel Said", ShiftHoursPerWeek = 38, Salary = 50200, IsOnDuty = true, DepartmentId = 38 },
            new() { Id = 39, Name = "Nurse Inas Mansour", ShiftHoursPerWeek = 40, Salary = 50600, IsOnDuty = false, DepartmentId = 39 },
            new() { Id = 40, Name = "Nurse Magdy Zaki", ShiftHoursPerWeek = 32, Salary = 51000, IsOnDuty = true, DepartmentId = 40 },
            new() { Id = 41, Name = "Nurse Hala Barakat", ShiftHoursPerWeek = 34, Salary = 51400, IsOnDuty = false, DepartmentId = 41 },
            new() { Id = 42, Name = "Nurse Fares Ashraf", ShiftHoursPerWeek = 36, Salary = 51800, IsOnDuty = true, DepartmentId = 42 },
            new() { Id = 43, Name = "Nurse Jana Shaaban", ShiftHoursPerWeek = 38, Salary = 52200, IsOnDuty = false, DepartmentId = 43 },
            new() { Id = 44, Name = "Nurse Ahmed Salah", ShiftHoursPerWeek = 40, Salary = 52600, IsOnDuty = true, DepartmentId = 44 },
            new() { Id = 45, Name = "Nurse Mona Samir", ShiftHoursPerWeek = 32, Salary = 53000, IsOnDuty = false, DepartmentId = 45 },
            new() { Id = 46, Name = "Nurse Karim Khalil", ShiftHoursPerWeek = 34, Salary = 53400, IsOnDuty = true, DepartmentId = 46 },
            new() { Id = 47, Name = "Nurse Yara Adel", ShiftHoursPerWeek = 36, Salary = 53800, IsOnDuty = false, DepartmentId = 47 },
            new() { Id = 48, Name = "Nurse Tarek Said", ShiftHoursPerWeek = 38, Salary = 54200, IsOnDuty = true, DepartmentId = 48 },
            new() { Id = 49, Name = "Nurse Salma Mansour", ShiftHoursPerWeek = 40, Salary = 54600, IsOnDuty = false, DepartmentId = 49 },
            new() { Id = 50, Name = "Nurse Omar Zaki", ShiftHoursPerWeek = 32, Salary = 55000, IsOnDuty = true, DepartmentId = 50 }
        };

        public static List<Patient> Patients { get; } = new()
        {
            new() { Id = 1, Name = "Yara Adel", Age = 4, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 2, Name = "Tarek Said", Age = 7, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 3, Name = "Salma Mansour", Age = 10, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 4, Name = "Omar Zaki", Age = 13, Gender = Gender.Male, HasInsurance = false, OutstandingBalance = 260 },
            new() { Id = 5, Name = "Nour Barakat", Age = 16, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 300 },
            new() { Id = 6, Name = "Sara Ashraf", Age = 19, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 7, Name = "Mostafa Shaaban", Age = 22, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 8, Name = "Laila Salah", Age = 25, Gender = Gender.Female, HasInsurance = false, OutstandingBalance = 420 },
            new() { Id = 9, Name = "Hoda Samir", Age = 28, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 10, Name = "Youssef Khalil", Age = 31, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 300 },
            new() { Id = 11, Name = "Amina Adel", Age = 34, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 12, Name = "Hassan Said", Age = 37, Gender = Gender.Other, HasInsurance = false, OutstandingBalance = 580 },
            new() { Id = 13, Name = "Fatma Mansour", Age = 40, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 14, Name = "Ali Zaki", Age = 43, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 15, Name = "Dina Barakat", Age = 46, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 300 },
            new() { Id = 16, Name = "Rami Ashraf", Age = 49, Gender = Gender.Male, HasInsurance = false, OutstandingBalance = 740 },
            new() { Id = 17, Name = "Heba Shaaban", Age = 52, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 18, Name = "Mahmoud Salah", Age = 55, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 19, Name = "Nadine Samir", Age = 58, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 20, Name = "Khaled Khalil", Age = 61, Gender = Gender.Female, HasInsurance = false, OutstandingBalance = 900 },
            new() { Id = 21, Name = "Rania Adel", Age = 64, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 22, Name = "Samir Said", Age = 67, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 23, Name = "Layla Mansour", Age = 70, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 24, Name = "Fady Zaki", Age = 73, Gender = Gender.Other, HasInsurance = false, OutstandingBalance = 1060 },
            new() { Id = 25, Name = "Farida Barakat", Age = 76, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 300 },
            new() { Id = 26, Name = "Walid Ashraf", Age = 79, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 27, Name = "Hanan Shaaban", Age = 82, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 28, Name = "Ziad Salah", Age = 85, Gender = Gender.Male, HasInsurance = false, OutstandingBalance = 1220 },
            new() { Id = 29, Name = "Marwa Samir", Age = 88, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 30, Name = "Bassem Khalil", Age = 1, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 300 },
            new() { Id = 31, Name = "Noha Adel", Age = 4, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 32, Name = "Sherif Said", Age = 7, Gender = Gender.Female, HasInsurance = false, OutstandingBalance = 1380 },
            new() { Id = 33, Name = "Ghada Mansour", Age = 10, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 34, Name = "Amr Zaki", Age = 13, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 35, Name = "Reem Barakat", Age = 16, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 300 },
            new() { Id = 36, Name = "Hisham Ashraf", Age = 19, Gender = Gender.Other, HasInsurance = false, OutstandingBalance = 1540 },
            new() { Id = 37, Name = "Dalia Shaaban", Age = 22, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 38, Name = "Ehab Salah", Age = 25, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 39, Name = "Mayada Samir", Age = 28, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 40, Name = "Tamer Khalil", Age = 31, Gender = Gender.Male, HasInsurance = false, OutstandingBalance = 1700 },
            new() { Id = 41, Name = "Shereen Adel", Age = 34, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 42, Name = "Adel Said", Age = 37, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 43, Name = "Inas Mansour", Age = 40, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 44, Name = "Magdy Zaki", Age = 43, Gender = Gender.Female, HasInsurance = false, OutstandingBalance = 1860 },
            new() { Id = 45, Name = "Hala Barakat", Age = 46, Gender = Gender.Other, HasInsurance = true, OutstandingBalance = 300 },
            new() { Id = 46, Name = "Fares Ashraf", Age = 49, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 47, Name = "Jana Shaaban", Age = 52, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 48, Name = "Ahmed Salah", Age = 55, Gender = Gender.Other, HasInsurance = false, OutstandingBalance = 2020 },
            new() { Id = 49, Name = "Mona Samir", Age = 58, Gender = Gender.Male, HasInsurance = true, OutstandingBalance = 0 },
            new() { Id = 50, Name = "Karim Khalil", Age = 61, Gender = Gender.Female, HasInsurance = true, OutstandingBalance = 300 }
        };

        public static List<Room> Rooms { get; } = new()
        {
            new() { Id = 1, RoomNumber = 101, Type = RoomType.General, IsOccupied = true, DailyRate = 450, DepartmentId = 1 },
            new() { Id = 2, RoomNumber = 102, Type = RoomType.ICU, IsOccupied = true, DailyRate = 500, DepartmentId = 2 },
            new() { Id = 3, RoomNumber = 103, Type = RoomType.Operation, IsOccupied = false, DailyRate = 550, DepartmentId = 3 },
            new() { Id = 4, RoomNumber = 104, Type = RoomType.Emergency, IsOccupied = true, DailyRate = 600, DepartmentId = 4 },
            new() { Id = 5, RoomNumber = 105, Type = RoomType.Maternity, IsOccupied = true, DailyRate = 650, DepartmentId = 5 },
            new() { Id = 6, RoomNumber = 106, Type = RoomType.General, IsOccupied = false, DailyRate = 700, DepartmentId = 6 },
            new() { Id = 7, RoomNumber = 107, Type = RoomType.ICU, IsOccupied = true, DailyRate = 750, DepartmentId = 7 },
            new() { Id = 8, RoomNumber = 108, Type = RoomType.Operation, IsOccupied = true, DailyRate = 800, DepartmentId = 8 },
            new() { Id = 9, RoomNumber = 109, Type = RoomType.Emergency, IsOccupied = false, DailyRate = 850, DepartmentId = 9 },
            new() { Id = 10, RoomNumber = 110, Type = RoomType.Maternity, IsOccupied = true, DailyRate = 900, DepartmentId = 10 },
            new() { Id = 11, RoomNumber = 111, Type = RoomType.General, IsOccupied = true, DailyRate = 950, DepartmentId = 11 },
            new() { Id = 12, RoomNumber = 112, Type = RoomType.ICU, IsOccupied = false, DailyRate = 1000, DepartmentId = 12 },
            new() { Id = 13, RoomNumber = 113, Type = RoomType.Operation, IsOccupied = true, DailyRate = 1050, DepartmentId = 13 },
            new() { Id = 14, RoomNumber = 114, Type = RoomType.Emergency, IsOccupied = true, DailyRate = 1100, DepartmentId = 14 },
            new() { Id = 15, RoomNumber = 115, Type = RoomType.Maternity, IsOccupied = false, DailyRate = 1150, DepartmentId = 15 },
            new() { Id = 16, RoomNumber = 116, Type = RoomType.General, IsOccupied = true, DailyRate = 1200, DepartmentId = 16 },
            new() { Id = 17, RoomNumber = 117, Type = RoomType.ICU, IsOccupied = true, DailyRate = 1250, DepartmentId = 17 },
            new() { Id = 18, RoomNumber = 118, Type = RoomType.Operation, IsOccupied = false, DailyRate = 1300, DepartmentId = 18 },
            new() { Id = 19, RoomNumber = 119, Type = RoomType.Emergency, IsOccupied = true, DailyRate = 1350, DepartmentId = 19 },
            new() { Id = 20, RoomNumber = 120, Type = RoomType.Maternity, IsOccupied = true, DailyRate = 1400, DepartmentId = 20 },
            new() { Id = 21, RoomNumber = 121, Type = RoomType.General, IsOccupied = false, DailyRate = 1450, DepartmentId = 21 },
            new() { Id = 22, RoomNumber = 122, Type = RoomType.ICU, IsOccupied = true, DailyRate = 1500, DepartmentId = 22 },
            new() { Id = 23, RoomNumber = 123, Type = RoomType.Operation, IsOccupied = true, DailyRate = 1550, DepartmentId = 23 },
            new() { Id = 24, RoomNumber = 124, Type = RoomType.Emergency, IsOccupied = false, DailyRate = 1600, DepartmentId = 24 },
            new() { Id = 25, RoomNumber = 125, Type = RoomType.Maternity, IsOccupied = true, DailyRate = 1650, DepartmentId = 25 },
            new() { Id = 26, RoomNumber = 126, Type = RoomType.General, IsOccupied = true, DailyRate = 1700, DepartmentId = 26 },
            new() { Id = 27, RoomNumber = 127, Type = RoomType.ICU, IsOccupied = false, DailyRate = 1750, DepartmentId = 27 },
            new() { Id = 28, RoomNumber = 128, Type = RoomType.Operation, IsOccupied = true, DailyRate = 1800, DepartmentId = 28 },
            new() { Id = 29, RoomNumber = 129, Type = RoomType.Emergency, IsOccupied = true, DailyRate = 1850, DepartmentId = 29 },
            new() { Id = 30, RoomNumber = 130, Type = RoomType.Maternity, IsOccupied = false, DailyRate = 1900, DepartmentId = 30 },
            new() { Id = 31, RoomNumber = 131, Type = RoomType.General, IsOccupied = true, DailyRate = 1950, DepartmentId = 31 },
            new() { Id = 32, RoomNumber = 132, Type = RoomType.ICU, IsOccupied = true, DailyRate = 2000, DepartmentId = 32 },
            new() { Id = 33, RoomNumber = 133, Type = RoomType.Operation, IsOccupied = false, DailyRate = 2050, DepartmentId = 33 },
            new() { Id = 34, RoomNumber = 134, Type = RoomType.Emergency, IsOccupied = true, DailyRate = 2100, DepartmentId = 34 },
            new() { Id = 35, RoomNumber = 135, Type = RoomType.Maternity, IsOccupied = true, DailyRate = 2150, DepartmentId = 35 },
            new() { Id = 36, RoomNumber = 136, Type = RoomType.General, IsOccupied = false, DailyRate = 2200, DepartmentId = 36 },
            new() { Id = 37, RoomNumber = 137, Type = RoomType.ICU, IsOccupied = true, DailyRate = 2250, DepartmentId = 37 },
            new() { Id = 38, RoomNumber = 138, Type = RoomType.Operation, IsOccupied = true, DailyRate = 2300, DepartmentId = 38 },
            new() { Id = 39, RoomNumber = 139, Type = RoomType.Emergency, IsOccupied = false, DailyRate = 2350, DepartmentId = 39 },
            new() { Id = 40, RoomNumber = 140, Type = RoomType.Maternity, IsOccupied = true, DailyRate = 2400, DepartmentId = 40 },
            new() { Id = 41, RoomNumber = 141, Type = RoomType.General, IsOccupied = true, DailyRate = 2450, DepartmentId = 41 },
            new() { Id = 42, RoomNumber = 142, Type = RoomType.ICU, IsOccupied = false, DailyRate = 2500, DepartmentId = 42 },
            new() { Id = 43, RoomNumber = 143, Type = RoomType.Operation, IsOccupied = true, DailyRate = 2550, DepartmentId = 43 },
            new() { Id = 44, RoomNumber = 144, Type = RoomType.Emergency, IsOccupied = true, DailyRate = 2600, DepartmentId = 44 },
            new() { Id = 45, RoomNumber = 145, Type = RoomType.Maternity, IsOccupied = false, DailyRate = 2650, DepartmentId = 45 },
            new() { Id = 46, RoomNumber = 146, Type = RoomType.General, IsOccupied = true, DailyRate = 2700, DepartmentId = 46 },
            new() { Id = 47, RoomNumber = 147, Type = RoomType.ICU, IsOccupied = true, DailyRate = 2750, DepartmentId = 47 },
            new() { Id = 48, RoomNumber = 148, Type = RoomType.Operation, IsOccupied = false, DailyRate = 2800, DepartmentId = 48 },
            new() { Id = 49, RoomNumber = 149, Type = RoomType.Emergency, IsOccupied = true, DailyRate = 2850, DepartmentId = 49 },
            new() { Id = 50, RoomNumber = 150, Type = RoomType.Maternity, IsOccupied = true, DailyRate = 2900, DepartmentId = 50 }
        };

        public static List<Appointment> Appointments { get; } = new()
        {
            new() { Id = 1, Date = new DateTime(2026, 1, 1), Status = AppointmentStatus.Scheduled, Cost = 215, IsEmergency = false, DoctorId = 1, PatientId = 3, RoomId = 2 },
            new() { Id = 2, Date = new DateTime(2026, 2, 2), Status = AppointmentStatus.Completed, Cost = 230, IsEmergency = false, DoctorId = 2, PatientId = 6, RoomId = 4 },
            new() { Id = 3, Date = new DateTime(2026, 3, 3), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = false, DoctorId = 3, PatientId = 9, RoomId = 6 },
            new() { Id = 4, Date = new DateTime(2026, 4, 4), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = false, DoctorId = 4, PatientId = 12, RoomId = 8 },
            new() { Id = 5, Date = new DateTime(2026, 5, 5), Status = AppointmentStatus.Scheduled, Cost = 275, IsEmergency = false, DoctorId = 5, PatientId = 15, RoomId = 10 },
            new() { Id = 6, Date = new DateTime(2026, 6, 6), Status = AppointmentStatus.Completed, Cost = 290, IsEmergency = false, DoctorId = 6, PatientId = 18, RoomId = 12 },
            new() { Id = 7, Date = new DateTime(2026, 1, 7), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = true, DoctorId = 7, PatientId = 21, RoomId = 14 },
            new() { Id = 8, Date = new DateTime(2026, 2, 8), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = false, DoctorId = 8, PatientId = 24, RoomId = 16 },
            new() { Id = 9, Date = new DateTime(2026, 3, 9), Status = AppointmentStatus.Scheduled, Cost = 335, IsEmergency = false, DoctorId = 9, PatientId = 27, RoomId = 18 },
            new() { Id = 10, Date = new DateTime(2026, 4, 10), Status = AppointmentStatus.Completed, Cost = 350, IsEmergency = false, DoctorId = 10, PatientId = 30, RoomId = 20 },
            new() { Id = 11, Date = new DateTime(2026, 5, 11), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = false, DoctorId = 11, PatientId = 33, RoomId = 22 },
            new() { Id = 12, Date = new DateTime(2026, 6, 12), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = false, DoctorId = 12, PatientId = 36, RoomId = 24 },
            new() { Id = 13, Date = new DateTime(2026, 1, 13), Status = AppointmentStatus.Scheduled, Cost = 395, IsEmergency = false, DoctorId = 13, PatientId = 39, RoomId = 26 },
            new() { Id = 14, Date = new DateTime(2026, 2, 14), Status = AppointmentStatus.Completed, Cost = 1340, IsEmergency = true, DoctorId = 14, PatientId = 42, RoomId = 28 },
            new() { Id = 15, Date = new DateTime(2026, 3, 15), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = false, DoctorId = 15, PatientId = 45, RoomId = 30 },
            new() { Id = 16, Date = new DateTime(2026, 4, 16), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = false, DoctorId = 16, PatientId = 48, RoomId = 32 },
            new() { Id = 17, Date = new DateTime(2026, 5, 17), Status = AppointmentStatus.Scheduled, Cost = 455, IsEmergency = false, DoctorId = 17, PatientId = 1, RoomId = 34 },
            new() { Id = 18, Date = new DateTime(2026, 6, 18), Status = AppointmentStatus.Completed, Cost = 470, IsEmergency = false, DoctorId = 18, PatientId = 4, RoomId = 36 },
            new() { Id = 19, Date = new DateTime(2026, 1, 19), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = false, DoctorId = 19, PatientId = 7, RoomId = 38 },
            new() { Id = 20, Date = new DateTime(2026, 2, 20), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = false, DoctorId = 20, PatientId = 10, RoomId = 40 },
            new() { Id = 21, Date = new DateTime(2026, 3, 21), Status = AppointmentStatus.Scheduled, Cost = 1410, IsEmergency = true, DoctorId = 21, PatientId = 13, RoomId = 42 },
            new() { Id = 22, Date = new DateTime(2026, 4, 22), Status = AppointmentStatus.Completed, Cost = 530, IsEmergency = false, DoctorId = 22, PatientId = 16, RoomId = 44 },
            new() { Id = 23, Date = new DateTime(2026, 5, 23), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = false, DoctorId = 23, PatientId = 19, RoomId = 46 },
            new() { Id = 24, Date = new DateTime(2026, 6, 24), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = false, DoctorId = 24, PatientId = 22, RoomId = 48 },
            new() { Id = 25, Date = new DateTime(2026, 1, 25), Status = AppointmentStatus.Scheduled, Cost = 575, IsEmergency = false, DoctorId = 25, PatientId = 25, RoomId = 50 },
            new() { Id = 26, Date = new DateTime(2026, 2, 26), Status = AppointmentStatus.Completed, Cost = 590, IsEmergency = false, DoctorId = 26, PatientId = 28, RoomId = 2 },
            new() { Id = 27, Date = new DateTime(2026, 3, 27), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = false, DoctorId = 27, PatientId = 31, RoomId = 4 },
            new() { Id = 28, Date = new DateTime(2026, 4, 28), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = true, DoctorId = 28, PatientId = 34, RoomId = 6 },
            new() { Id = 29, Date = new DateTime(2026, 5, 2), Status = AppointmentStatus.Scheduled, Cost = 635, IsEmergency = false, DoctorId = 29, PatientId = 37, RoomId = 8 },
            new() { Id = 30, Date = new DateTime(2026, 6, 3), Status = AppointmentStatus.Completed, Cost = 650, IsEmergency = false, DoctorId = 30, PatientId = 40, RoomId = 10 },
            new() { Id = 31, Date = new DateTime(2026, 1, 4), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = false, DoctorId = 31, PatientId = 43, RoomId = 12 },
            new() { Id = 32, Date = new DateTime(2026, 2, 5), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = false, DoctorId = 32, PatientId = 46, RoomId = 14 },
            new() { Id = 33, Date = new DateTime(2026, 3, 6), Status = AppointmentStatus.Scheduled, Cost = 695, IsEmergency = false, DoctorId = 33, PatientId = 49, RoomId = 16 },
            new() { Id = 34, Date = new DateTime(2026, 4, 7), Status = AppointmentStatus.Completed, Cost = 710, IsEmergency = false, DoctorId = 34, PatientId = 2, RoomId = 18 },
            new() { Id = 35, Date = new DateTime(2026, 5, 8), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = true, DoctorId = 35, PatientId = 5, RoomId = 20 },
            new() { Id = 36, Date = new DateTime(2026, 6, 9), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = false, DoctorId = 36, PatientId = 8, RoomId = 22 },
            new() { Id = 37, Date = new DateTime(2026, 1, 10), Status = AppointmentStatus.Scheduled, Cost = 755, IsEmergency = false, DoctorId = 37, PatientId = 11, RoomId = 24 },
            new() { Id = 38, Date = new DateTime(2026, 2, 11), Status = AppointmentStatus.Completed, Cost = 770, IsEmergency = false, DoctorId = 38, PatientId = 14, RoomId = 26 },
            new() { Id = 39, Date = new DateTime(2026, 3, 12), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = false, DoctorId = 39, PatientId = 17, RoomId = 28 },
            new() { Id = 40, Date = new DateTime(2026, 4, 13), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = false, DoctorId = 40, PatientId = 20, RoomId = 30 },
            new() { Id = 41, Date = new DateTime(2026, 5, 14), Status = AppointmentStatus.Scheduled, Cost = 815, IsEmergency = false, DoctorId = 41, PatientId = 23, RoomId = 32 },
            new() { Id = 42, Date = new DateTime(2026, 6, 15), Status = AppointmentStatus.Completed, Cost = 1620, IsEmergency = true, DoctorId = 42, PatientId = 26, RoomId = 34 },
            new() { Id = 43, Date = new DateTime(2026, 1, 16), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = false, DoctorId = 43, PatientId = 29, RoomId = 36 },
            new() { Id = 44, Date = new DateTime(2026, 2, 17), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = false, DoctorId = 44, PatientId = 32, RoomId = 38 },
            new() { Id = 45, Date = new DateTime(2026, 3, 18), Status = AppointmentStatus.Scheduled, Cost = 875, IsEmergency = false, DoctorId = 45, PatientId = 35, RoomId = 40 },
            new() { Id = 46, Date = new DateTime(2026, 4, 19), Status = AppointmentStatus.Completed, Cost = 890, IsEmergency = false, DoctorId = 46, PatientId = 38, RoomId = 42 },
            new() { Id = 47, Date = new DateTime(2026, 5, 20), Status = AppointmentStatus.Cancelled, Cost = 0, IsEmergency = false, DoctorId = 47, PatientId = 41, RoomId = 44 },
            new() { Id = 48, Date = new DateTime(2026, 6, 21), Status = AppointmentStatus.NoShow, Cost = 0, IsEmergency = false, DoctorId = 48, PatientId = 44, RoomId = 46 },
            new() { Id = 49, Date = new DateTime(2026, 1, 22), Status = AppointmentStatus.Scheduled, Cost = 1690, IsEmergency = true, DoctorId = 49, PatientId = 47, RoomId = 48 },
            new() { Id = 50, Date = new DateTime(2026, 2, 23), Status = AppointmentStatus.Completed, Cost = 950, IsEmergency = false, DoctorId = 50, PatientId = 50, RoomId = 50 }
        };

        public static List<MedicalRecord> MedicalRecords { get; } = new()
        {
            new() { Id = 1, Date = new DateTime(2026, 1, 1), Diagnosis = "Hypertension", Notes = "Follow-up required", IsChronic = false, PatientId = 1, DoctorId = 2 },
            new() { Id = 2, Date = new DateTime(2026, 2, 2), Diagnosis = "Flu", Notes = "Stable", IsChronic = false, PatientId = 2, DoctorId = 4 },
            new() { Id = 3, Date = new DateTime(2026, 3, 3), Diagnosis = "Fracture", Notes = "Follow-up required", IsChronic = false, PatientId = 3, DoctorId = 6 },
            new() { Id = 4, Date = new DateTime(2026, 4, 4), Diagnosis = "Diabetes", Notes = "Stable", IsChronic = true, PatientId = 4, DoctorId = 8 },
            new() { Id = 5, Date = new DateTime(2026, 5, 5), Diagnosis = "Asthma", Notes = "Follow-up required", IsChronic = false, PatientId = 5, DoctorId = 10 },
            new() { Id = 6, Date = new DateTime(2026, 6, 6), Diagnosis = "Migraine", Notes = "Stable", IsChronic = false, PatientId = 6, DoctorId = 12 },
            new() { Id = 7, Date = new DateTime(2026, 1, 7), Diagnosis = "Allergy", Notes = "Follow-up required", IsChronic = false, PatientId = 7, DoctorId = 14 },
            new() { Id = 8, Date = new DateTime(2026, 2, 8), Diagnosis = "Anemia", Notes = "Stable", IsChronic = true, PatientId = 8, DoctorId = 16 },
            new() { Id = 9, Date = new DateTime(2026, 3, 9), Diagnosis = "Infection", Notes = "Follow-up required", IsChronic = false, PatientId = 9, DoctorId = 18 },
            new() { Id = 10, Date = new DateTime(2026, 4, 10), Diagnosis = "Sprain", Notes = "Stable", IsChronic = false, PatientId = 10, DoctorId = 20 },
            new() { Id = 11, Date = new DateTime(2026, 5, 11), Diagnosis = "Bronchitis", Notes = "Follow-up required", IsChronic = false, PatientId = 11, DoctorId = 22 },
            new() { Id = 12, Date = new DateTime(2026, 6, 12), Diagnosis = "Gastritis", Notes = "Stable", IsChronic = true, PatientId = 12, DoctorId = 24 },
            new() { Id = 13, Date = new DateTime(2026, 1, 13), Diagnosis = "Arthritis", Notes = "Follow-up required", IsChronic = false, PatientId = 13, DoctorId = 26 },
            new() { Id = 14, Date = new DateTime(2026, 2, 14), Diagnosis = "Anxiety", Notes = "Stable", IsChronic = false, PatientId = 14, DoctorId = 28 },
            new() { Id = 15, Date = new DateTime(2026, 3, 15), Diagnosis = "Tonsillitis", Notes = "Follow-up required", IsChronic = false, PatientId = 15, DoctorId = 30 },
            new() { Id = 16, Date = new DateTime(2026, 4, 16), Diagnosis = "Sinusitis", Notes = "Stable", IsChronic = true, PatientId = 16, DoctorId = 32 },
            new() { Id = 17, Date = new DateTime(2026, 5, 17), Diagnosis = "Eczema", Notes = "Follow-up required", IsChronic = false, PatientId = 17, DoctorId = 34 },
            new() { Id = 18, Date = new DateTime(2026, 6, 18), Diagnosis = "UTI", Notes = "Stable", IsChronic = false, PatientId = 18, DoctorId = 36 },
            new() { Id = 19, Date = new DateTime(2026, 1, 19), Diagnosis = "Back pain", Notes = "Follow-up required", IsChronic = false, PatientId = 19, DoctorId = 38 },
            new() { Id = 20, Date = new DateTime(2026, 2, 20), Diagnosis = "Pneumonia", Notes = "Stable", IsChronic = true, PatientId = 20, DoctorId = 40 },
            new() { Id = 21, Date = new DateTime(2026, 3, 21), Diagnosis = "Hypertension", Notes = "Follow-up required", IsChronic = false, PatientId = 21, DoctorId = 42 },
            new() { Id = 22, Date = new DateTime(2026, 4, 22), Diagnosis = "Flu", Notes = "Stable", IsChronic = false, PatientId = 22, DoctorId = 44 },
            new() { Id = 23, Date = new DateTime(2026, 5, 23), Diagnosis = "Fracture", Notes = "Follow-up required", IsChronic = false, PatientId = 23, DoctorId = 46 },
            new() { Id = 24, Date = new DateTime(2026, 6, 24), Diagnosis = "Diabetes", Notes = "Stable", IsChronic = true, PatientId = 24, DoctorId = 48 },
            new() { Id = 25, Date = new DateTime(2026, 1, 25), Diagnosis = "Asthma", Notes = "Follow-up required", IsChronic = false, PatientId = 25, DoctorId = 50 },
            new() { Id = 26, Date = new DateTime(2026, 2, 26), Diagnosis = "Migraine", Notes = "Stable", IsChronic = false, PatientId = 26, DoctorId = 2 },
            new() { Id = 27, Date = new DateTime(2026, 3, 27), Diagnosis = "Allergy", Notes = "Follow-up required", IsChronic = false, PatientId = 27, DoctorId = 4 },
            new() { Id = 28, Date = new DateTime(2026, 4, 28), Diagnosis = "Anemia", Notes = "Stable", IsChronic = true, PatientId = 28, DoctorId = 6 },
            new() { Id = 29, Date = new DateTime(2026, 5, 1), Diagnosis = "Infection", Notes = "Follow-up required", IsChronic = false, PatientId = 29, DoctorId = 8 },
            new() { Id = 30, Date = new DateTime(2026, 6, 2), Diagnosis = "Sprain", Notes = "Stable", IsChronic = false, PatientId = 30, DoctorId = 10 },
            new() { Id = 31, Date = new DateTime(2026, 1, 3), Diagnosis = "Bronchitis", Notes = "Follow-up required", IsChronic = false, PatientId = 31, DoctorId = 12 },
            new() { Id = 32, Date = new DateTime(2026, 2, 4), Diagnosis = "Gastritis", Notes = "Stable", IsChronic = true, PatientId = 32, DoctorId = 14 },
            new() { Id = 33, Date = new DateTime(2026, 3, 5), Diagnosis = "Arthritis", Notes = "Follow-up required", IsChronic = false, PatientId = 33, DoctorId = 16 },
            new() { Id = 34, Date = new DateTime(2026, 4, 6), Diagnosis = "Anxiety", Notes = "Stable", IsChronic = false, PatientId = 34, DoctorId = 18 },
            new() { Id = 35, Date = new DateTime(2026, 5, 7), Diagnosis = "Tonsillitis", Notes = "Follow-up required", IsChronic = false, PatientId = 35, DoctorId = 20 },
            new() { Id = 36, Date = new DateTime(2026, 6, 8), Diagnosis = "Sinusitis", Notes = "Stable", IsChronic = true, PatientId = 36, DoctorId = 22 },
            new() { Id = 37, Date = new DateTime(2026, 1, 9), Diagnosis = "Eczema", Notes = "Follow-up required", IsChronic = false, PatientId = 37, DoctorId = 24 },
            new() { Id = 38, Date = new DateTime(2026, 2, 10), Diagnosis = "UTI", Notes = "Stable", IsChronic = false, PatientId = 38, DoctorId = 26 },
            new() { Id = 39, Date = new DateTime(2026, 3, 11), Diagnosis = "Back pain", Notes = "Follow-up required", IsChronic = false, PatientId = 39, DoctorId = 28 },
            new() { Id = 40, Date = new DateTime(2026, 4, 12), Diagnosis = "Pneumonia", Notes = "Stable", IsChronic = true, PatientId = 40, DoctorId = 30 },
            new() { Id = 41, Date = new DateTime(2026, 5, 13), Diagnosis = "Hypertension", Notes = "Follow-up required", IsChronic = false, PatientId = 41, DoctorId = 32 },
            new() { Id = 42, Date = new DateTime(2026, 6, 14), Diagnosis = "Flu", Notes = "Stable", IsChronic = false, PatientId = 42, DoctorId = 34 },
            new() { Id = 43, Date = new DateTime(2026, 1, 15), Diagnosis = "Fracture", Notes = "Follow-up required", IsChronic = false, PatientId = 43, DoctorId = 36 },
            new() { Id = 44, Date = new DateTime(2026, 2, 16), Diagnosis = "Diabetes", Notes = "Stable", IsChronic = true, PatientId = 44, DoctorId = 38 },
            new() { Id = 45, Date = new DateTime(2026, 3, 17), Diagnosis = "Asthma", Notes = "Follow-up required", IsChronic = false, PatientId = 45, DoctorId = 40 },
            new() { Id = 46, Date = new DateTime(2026, 4, 18), Diagnosis = "Migraine", Notes = "Stable", IsChronic = false, PatientId = 46, DoctorId = 42 },
            new() { Id = 47, Date = new DateTime(2026, 5, 19), Diagnosis = "Allergy", Notes = "Follow-up required", IsChronic = false, PatientId = 47, DoctorId = 44 },
            new() { Id = 48, Date = new DateTime(2026, 6, 20), Diagnosis = "Anemia", Notes = "Stable", IsChronic = true, PatientId = 48, DoctorId = 46 },
            new() { Id = 49, Date = new DateTime(2026, 1, 21), Diagnosis = "Infection", Notes = "Follow-up required", IsChronic = false, PatientId = 49, DoctorId = 48 },
            new() { Id = 50, Date = new DateTime(2026, 2, 22), Diagnosis = "Sprain", Notes = "Stable", IsChronic = false, PatientId = 50, DoctorId = 50 }
        };

        public static List<Medication> Medications { get; } = new()
        {
            new() { Id = 1, Name = "Amoxicillin", PricePerUnit = 1.35, RequiresPrescription = true, StockQuantity = 70 },
            new() { Id = 2, Name = "Ibuprofen", PricePerUnit = 1.7, RequiresPrescription = true, StockQuantity = 90 },
            new() { Id = 3, Name = "Metformin", PricePerUnit = 2.05, RequiresPrescription = false, StockQuantity = 110 },
            new() { Id = 4, Name = "Insulin", PricePerUnit = 2.4, RequiresPrescription = true, StockQuantity = 130 },
            new() { Id = 5, Name = "Paracetamol", PricePerUnit = 2.75, RequiresPrescription = true, StockQuantity = 150 },
            new() { Id = 6, Name = "Aspirin", PricePerUnit = 3.1, RequiresPrescription = false, StockQuantity = 170 },
            new() { Id = 7, Name = "Omeprazole", PricePerUnit = 3.45, RequiresPrescription = true, StockQuantity = 190 },
            new() { Id = 8, Name = "Atorvastatin", PricePerUnit = 3.8, RequiresPrescription = true, StockQuantity = 210 },
            new() { Id = 9, Name = "Losartan", PricePerUnit = 4.15, RequiresPrescription = false, StockQuantity = 230 },
            new() { Id = 10, Name = "Cetirizine", PricePerUnit = 4.5, RequiresPrescription = true, StockQuantity = 250 },
            new() { Id = 11, Name = "Azithromycin", PricePerUnit = 4.85, RequiresPrescription = true, StockQuantity = 270 },
            new() { Id = 12, Name = "Diclofenac", PricePerUnit = 5.2, RequiresPrescription = false, StockQuantity = 290 },
            new() { Id = 13, Name = "Amlodipine", PricePerUnit = 5.55, RequiresPrescription = true, StockQuantity = 310 },
            new() { Id = 14, Name = "Levothyroxine", PricePerUnit = 5.9, RequiresPrescription = true, StockQuantity = 330 },
            new() { Id = 15, Name = "Salbutamol", PricePerUnit = 6.25, RequiresPrescription = false, StockQuantity = 350 },
            new() { Id = 16, Name = "Prednisolone", PricePerUnit = 6.6, RequiresPrescription = true, StockQuantity = 370 },
            new() { Id = 17, Name = "Clopidogrel", PricePerUnit = 6.95, RequiresPrescription = true, StockQuantity = 390 },
            new() { Id = 18, Name = "Gabapentin", PricePerUnit = 7.3, RequiresPrescription = false, StockQuantity = 410 },
            new() { Id = 19, Name = "Sertraline", PricePerUnit = 7.65, RequiresPrescription = true, StockQuantity = 430 },
            new() { Id = 20, Name = "Pantoprazole", PricePerUnit = 8, RequiresPrescription = true, StockQuantity = 450 },
            new() { Id = 21, Name = "Ciprofloxacin", PricePerUnit = 8.35, RequiresPrescription = false, StockQuantity = 470 },
            new() { Id = 22, Name = "Doxycycline", PricePerUnit = 8.7, RequiresPrescription = true, StockQuantity = 490 },
            new() { Id = 23, Name = "Furosemide", PricePerUnit = 9.05, RequiresPrescription = true, StockQuantity = 510 },
            new() { Id = 24, Name = "Warfarin", PricePerUnit = 9.4, RequiresPrescription = false, StockQuantity = 530 },
            new() { Id = 25, Name = "Montelukast", PricePerUnit = 9.75, RequiresPrescription = true, StockQuantity = 550 },
            new() { Id = 26, Name = "Ranitidine", PricePerUnit = 10.1, RequiresPrescription = true, StockQuantity = 570 },
            new() { Id = 27, Name = "Tramadol", PricePerUnit = 10.45, RequiresPrescription = false, StockQuantity = 590 },
            new() { Id = 28, Name = "Morphine", PricePerUnit = 10.8, RequiresPrescription = true, StockQuantity = 610 },
            new() { Id = 29, Name = "Heparin", PricePerUnit = 11.15, RequiresPrescription = true, StockQuantity = 630 },
            new() { Id = 30, Name = "Vitamin D", PricePerUnit = 11.5, RequiresPrescription = false, StockQuantity = 650 },
            new() { Id = 31, Name = "Calcium", PricePerUnit = 11.85, RequiresPrescription = true, StockQuantity = 670 },
            new() { Id = 32, Name = "Iron sulfate", PricePerUnit = 12.2, RequiresPrescription = true, StockQuantity = 690 },
            new() { Id = 33, Name = "Folic acid", PricePerUnit = 12.55, RequiresPrescription = false, StockQuantity = 710 },
            new() { Id = 34, Name = "Lisinopril", PricePerUnit = 12.9, RequiresPrescription = true, StockQuantity = 730 },
            new() { Id = 35, Name = "Simvastatin", PricePerUnit = 13.25, RequiresPrescription = true, StockQuantity = 750 },
            new() { Id = 36, Name = "Metoprolol", PricePerUnit = 13.6, RequiresPrescription = false, StockQuantity = 770 },
            new() { Id = 37, Name = "Bisoprolol", PricePerUnit = 13.95, RequiresPrescription = true, StockQuantity = 790 },
            new() { Id = 38, Name = "Spironolactone", PricePerUnit = 14.3, RequiresPrescription = true, StockQuantity = 810 },
            new() { Id = 39, Name = "Allopurinol", PricePerUnit = 14.65, RequiresPrescription = false, StockQuantity = 830 },
            new() { Id = 40, Name = "Colchicine", PricePerUnit = 15, RequiresPrescription = true, StockQuantity = 850 },
            new() { Id = 41, Name = "Hydroxychloroquine", PricePerUnit = 15.35, RequiresPrescription = true, StockQuantity = 870 },
            new() { Id = 42, Name = "Methotrexate", PricePerUnit = 15.7, RequiresPrescription = false, StockQuantity = 890 },
            new() { Id = 43, Name = "Insulin Glargine", PricePerUnit = 16.05, RequiresPrescription = true, StockQuantity = 910 },
            new() { Id = 44, Name = "Insulin Aspart", PricePerUnit = 16.4, RequiresPrescription = true, StockQuantity = 930 },
            new() { Id = 45, Name = "Naproxen", PricePerUnit = 16.75, RequiresPrescription = false, StockQuantity = 950 },
            new() { Id = 46, Name = "Codeine", PricePerUnit = 17.1, RequiresPrescription = true, StockQuantity = 970 },
            new() { Id = 47, Name = "Orphenadrine", PricePerUnit = 17.45, RequiresPrescription = true, StockQuantity = 990 },
            new() { Id = 48, Name = "Multivitamin", PricePerUnit = 17.8, RequiresPrescription = false, StockQuantity = 1010 },
            new() { Id = 49, Name = "ORS sachets", PricePerUnit = 18.15, RequiresPrescription = true, StockQuantity = 1030 },
            new() { Id = 50, Name = "Antacid", PricePerUnit = 18.5, RequiresPrescription = true, StockQuantity = 1050 }
        };

        public static List<Prescription> Prescriptions { get; } = new()
        {
            new() { Id = 1, DateIssued = new DateTime(2026, 1, 1), Quantity = 6, Refillable = false, PatientId = 1, DoctorId = 3, MedicationId = 2 },
            new() { Id = 2, DateIssued = new DateTime(2026, 2, 2), Quantity = 7, Refillable = true, PatientId = 2, DoctorId = 6, MedicationId = 4 },
            new() { Id = 3, DateIssued = new DateTime(2026, 3, 3), Quantity = 8, Refillable = false, PatientId = 3, DoctorId = 9, MedicationId = 6 },
            new() { Id = 4, DateIssued = new DateTime(2026, 4, 4), Quantity = 9, Refillable = true, PatientId = 4, DoctorId = 12, MedicationId = 8 },
            new() { Id = 5, DateIssued = new DateTime(2026, 5, 5), Quantity = 10, Refillable = false, PatientId = 5, DoctorId = 15, MedicationId = 10 },
            new() { Id = 6, DateIssued = new DateTime(2026, 6, 6), Quantity = 11, Refillable = true, PatientId = 6, DoctorId = 18, MedicationId = 12 },
            new() { Id = 7, DateIssued = new DateTime(2026, 1, 7), Quantity = 12, Refillable = false, PatientId = 7, DoctorId = 21, MedicationId = 14 },
            new() { Id = 8, DateIssued = new DateTime(2026, 2, 8), Quantity = 13, Refillable = true, PatientId = 8, DoctorId = 24, MedicationId = 16 },
            new() { Id = 9, DateIssued = new DateTime(2026, 3, 9), Quantity = 14, Refillable = false, PatientId = 9, DoctorId = 27, MedicationId = 18 },
            new() { Id = 10, DateIssued = new DateTime(2026, 4, 10), Quantity = 15, Refillable = true, PatientId = 10, DoctorId = 30, MedicationId = 20 },
            new() { Id = 11, DateIssued = new DateTime(2026, 5, 11), Quantity = 16, Refillable = false, PatientId = 11, DoctorId = 33, MedicationId = 22 },
            new() { Id = 12, DateIssued = new DateTime(2026, 6, 12), Quantity = 17, Refillable = true, PatientId = 12, DoctorId = 36, MedicationId = 24 },
            new() { Id = 13, DateIssued = new DateTime(2026, 1, 13), Quantity = 18, Refillable = false, PatientId = 13, DoctorId = 39, MedicationId = 26 },
            new() { Id = 14, DateIssued = new DateTime(2026, 2, 14), Quantity = 19, Refillable = true, PatientId = 14, DoctorId = 42, MedicationId = 28 },
            new() { Id = 15, DateIssued = new DateTime(2026, 3, 15), Quantity = 20, Refillable = false, PatientId = 15, DoctorId = 45, MedicationId = 30 },
            new() { Id = 16, DateIssued = new DateTime(2026, 4, 16), Quantity = 21, Refillable = true, PatientId = 16, DoctorId = 48, MedicationId = 32 },
            new() { Id = 17, DateIssued = new DateTime(2026, 5, 17), Quantity = 22, Refillable = false, PatientId = 17, DoctorId = 1, MedicationId = 34 },
            new() { Id = 18, DateIssued = new DateTime(2026, 6, 18), Quantity = 23, Refillable = true, PatientId = 18, DoctorId = 4, MedicationId = 36 },
            new() { Id = 19, DateIssued = new DateTime(2026, 1, 19), Quantity = 24, Refillable = false, PatientId = 19, DoctorId = 7, MedicationId = 38 },
            new() { Id = 20, DateIssued = new DateTime(2026, 2, 20), Quantity = 25, Refillable = true, PatientId = 20, DoctorId = 10, MedicationId = 40 },
            new() { Id = 21, DateIssued = new DateTime(2026, 3, 21), Quantity = 26, Refillable = false, PatientId = 21, DoctorId = 13, MedicationId = 42 },
            new() { Id = 22, DateIssued = new DateTime(2026, 4, 22), Quantity = 27, Refillable = true, PatientId = 22, DoctorId = 16, MedicationId = 44 },
            new() { Id = 23, DateIssued = new DateTime(2026, 5, 23), Quantity = 28, Refillable = false, PatientId = 23, DoctorId = 19, MedicationId = 46 },
            new() { Id = 24, DateIssued = new DateTime(2026, 6, 24), Quantity = 29, Refillable = true, PatientId = 24, DoctorId = 22, MedicationId = 48 },
            new() { Id = 25, DateIssued = new DateTime(2026, 1, 25), Quantity = 30, Refillable = false, PatientId = 25, DoctorId = 25, MedicationId = 50 },
            new() { Id = 26, DateIssued = new DateTime(2026, 2, 26), Quantity = 31, Refillable = true, PatientId = 26, DoctorId = 28, MedicationId = 2 },
            new() { Id = 27, DateIssued = new DateTime(2026, 3, 27), Quantity = 32, Refillable = false, PatientId = 27, DoctorId = 31, MedicationId = 4 },
            new() { Id = 28, DateIssued = new DateTime(2026, 4, 28), Quantity = 33, Refillable = true, PatientId = 28, DoctorId = 34, MedicationId = 6 },
            new() { Id = 29, DateIssued = new DateTime(2026, 5, 1), Quantity = 34, Refillable = false, PatientId = 29, DoctorId = 37, MedicationId = 8 },
            new() { Id = 30, DateIssued = new DateTime(2026, 6, 2), Quantity = 35, Refillable = true, PatientId = 30, DoctorId = 40, MedicationId = 10 },
            new() { Id = 31, DateIssued = new DateTime(2026, 1, 3), Quantity = 36, Refillable = false, PatientId = 31, DoctorId = 43, MedicationId = 12 },
            new() { Id = 32, DateIssued = new DateTime(2026, 2, 4), Quantity = 37, Refillable = true, PatientId = 32, DoctorId = 46, MedicationId = 14 },
            new() { Id = 33, DateIssued = new DateTime(2026, 3, 5), Quantity = 38, Refillable = false, PatientId = 33, DoctorId = 49, MedicationId = 16 },
            new() { Id = 34, DateIssued = new DateTime(2026, 4, 6), Quantity = 39, Refillable = true, PatientId = 34, DoctorId = 2, MedicationId = 18 },
            new() { Id = 35, DateIssued = new DateTime(2026, 5, 7), Quantity = 40, Refillable = false, PatientId = 35, DoctorId = 5, MedicationId = 20 },
            new() { Id = 36, DateIssued = new DateTime(2026, 6, 8), Quantity = 41, Refillable = true, PatientId = 36, DoctorId = 8, MedicationId = 22 },
            new() { Id = 37, DateIssued = new DateTime(2026, 1, 9), Quantity = 42, Refillable = false, PatientId = 37, DoctorId = 11, MedicationId = 24 },
            new() { Id = 38, DateIssued = new DateTime(2026, 2, 10), Quantity = 43, Refillable = true, PatientId = 38, DoctorId = 14, MedicationId = 26 },
            new() { Id = 39, DateIssued = new DateTime(2026, 3, 11), Quantity = 44, Refillable = false, PatientId = 39, DoctorId = 17, MedicationId = 28 },
            new() { Id = 40, DateIssued = new DateTime(2026, 4, 12), Quantity = 5, Refillable = true, PatientId = 40, DoctorId = 20, MedicationId = 30 },
            new() { Id = 41, DateIssued = new DateTime(2026, 5, 13), Quantity = 6, Refillable = false, PatientId = 41, DoctorId = 23, MedicationId = 32 },
            new() { Id = 42, DateIssued = new DateTime(2026, 6, 14), Quantity = 7, Refillable = true, PatientId = 42, DoctorId = 26, MedicationId = 34 },
            new() { Id = 43, DateIssued = new DateTime(2026, 1, 15), Quantity = 8, Refillable = false, PatientId = 43, DoctorId = 29, MedicationId = 36 },
            new() { Id = 44, DateIssued = new DateTime(2026, 2, 16), Quantity = 9, Refillable = true, PatientId = 44, DoctorId = 32, MedicationId = 38 },
            new() { Id = 45, DateIssued = new DateTime(2026, 3, 17), Quantity = 10, Refillable = false, PatientId = 45, DoctorId = 35, MedicationId = 40 },
            new() { Id = 46, DateIssued = new DateTime(2026, 4, 18), Quantity = 11, Refillable = true, PatientId = 46, DoctorId = 38, MedicationId = 42 },
            new() { Id = 47, DateIssued = new DateTime(2026, 5, 19), Quantity = 12, Refillable = false, PatientId = 47, DoctorId = 41, MedicationId = 44 },
            new() { Id = 48, DateIssued = new DateTime(2026, 6, 20), Quantity = 13, Refillable = true, PatientId = 48, DoctorId = 44, MedicationId = 46 },
            new() { Id = 49, DateIssued = new DateTime(2026, 1, 21), Quantity = 14, Refillable = false, PatientId = 49, DoctorId = 47, MedicationId = 48 },
            new() { Id = 50, DateIssued = new DateTime(2026, 2, 22), Quantity = 15, Refillable = true, PatientId = 50, DoctorId = 50, MedicationId = 50 }
        };

        static HospitalSeeder()
        {
            WireNavigations();
        }

        // Links navigation collections by Id (not part of the seed data itself).
        private static void WireNavigations()
        {
            var doctorsByDept = Doctors.ToLookup(d => d.DepartmentId);
            var nursesByDept = Nurses.ToLookup(n => n.DepartmentId);
            var roomsByDept = Rooms.ToLookup(r => r.DepartmentId);
            var apptsByDoctor = Appointments.ToLookup(a => a.DoctorId);
            var apptsByPatient = Appointments.ToLookup(a => a.PatientId);
            var recordsByPatient = MedicalRecords.ToLookup(r => r.PatientId);
            var rxByPatient = Prescriptions.ToLookup(p => p.PatientId);

            Departments.ForEach(dept =>
            {
                dept.Doctors = doctorsByDept[dept.Id].ToList();
                dept.Nurses = nursesByDept[dept.Id].ToList();
                dept.Rooms = roomsByDept[dept.Id].ToList();
            });

            Hospitals.Select((h, i) =>
            {
                var start = (i * 2) % Departments.Count;
                h.Departments = new List<Department>
                {
                    Departments[start],
                    Departments[(start + 1) % Departments.Count]
                };
                return h;
            }).ToList();

            Doctors.ForEach(d => d.Appointments = apptsByDoctor[d.Id].ToList());
            Patients.ForEach(p =>
            {
                p.Appointments = apptsByPatient[p.Id].ToList();
                p.MedicalRecords = recordsByPatient[p.Id].ToList();
                p.Prescriptions = rxByPatient[p.Id].ToList();
            });
        }
    }
    #endregion

}
